/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as AdminRouteImport } from './../routes/admin'
import { Route as AcceptInviteRouteImport } from './../routes/accept-invite'
import { Route as appRouteRouteImport } from './../routes/(app)/route'
import { Route as appIndexRouteImport } from './../routes/(app)/index'
import { Route as authSignupRouteImport } from './../routes/(auth)/signup'
import { Route as authLoginRouteImport } from './../routes/(auth)/login'
import { Route as appUsersRouteImport } from './../routes/(app)/users'
import { Route as appTestRouteImport } from './../routes/(app)/test'
import { Route as appSyncLogsRouteImport } from './../routes/(app)/sync-logs'
import { Route as appSettingsRouteImport } from './../routes/(app)/settings'
import { Route as appReportsRouteImport } from './../routes/(app)/reports'
import { Route as appMenuMappingRouteImport } from './../routes/(app)/menu-mapping'
import { Route as appMenuRouteImport } from './../routes/(app)/menu'
import { Route as appLiveOrdersRouteImport } from './../routes/(app)/live-orders'
import { Route as appInventoryRouteImport } from './../routes/(app)/inventory'
import { Route as appIntegrationsRouteImport } from './../routes/(app)/integrations'
import { Route as appDashboardRouteImport } from './../routes/(app)/dashboard'
import { Route as appAnalyticsRouteImport } from './../routes/(app)/analytics'
import { Route as appAboutRouteImport } from './../routes/(app)/about'
import { Route as appReportsIndexRouteImport } from './../routes/(app)/reports/index'
import { Route as appReportsStockLevelsRouteImport } from './../routes/(app)/reports/stock-levels'
import { Route as appReportsSalesSummaryRouteImport } from './../routes/(app)/reports/sales-summary'
import { Route as appReportsMonthlyRevenueRouteImport } from './../routes/(app)/reports/monthly-revenue'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appUsersRoute = appUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => appRouteRoute,
} as any)
const appTestRoute = appTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => appRouteRoute,
} as any)
const appSyncLogsRoute = appSyncLogsRouteImport.update({
  id: '/sync-logs',
  path: '/sync-logs',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportsRoute = appReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => appRouteRoute,
} as any)
const appMenuMappingRoute = appMenuMappingRouteImport.update({
  id: '/menu-mapping',
  path: '/menu-mapping',
  getParentRoute: () => appRouteRoute,
} as any)
const appMenuRoute = appMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => appRouteRoute,
} as any)
const appLiveOrdersRoute = appLiveOrdersRouteImport.update({
  id: '/live-orders',
  path: '/live-orders',
  getParentRoute: () => appRouteRoute,
} as any)
const appInventoryRoute = appInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => appRouteRoute,
} as any)
const appIntegrationsRoute = appIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appAnalyticsRoute = appAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => appRouteRoute,
} as any)
const appAboutRoute = appAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportsIndexRoute = appReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appReportsRoute,
} as any)
const appReportsStockLevelsRoute = appReportsStockLevelsRouteImport.update({
  id: '/stock-levels',
  path: '/stock-levels',
  getParentRoute: () => appReportsRoute,
} as any)
const appReportsSalesSummaryRoute = appReportsSalesSummaryRouteImport.update({
  id: '/sales-summary',
  path: '/sales-summary',
  getParentRoute: () => appReportsRoute,
} as any)
const appReportsMonthlyRevenueRoute =
  appReportsMonthlyRevenueRouteImport.update({
    id: '/monthly-revenue',
    path: '/monthly-revenue',
    getParentRoute: () => appReportsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/about': typeof appAboutRoute
  '/analytics': typeof appAnalyticsRoute
  '/dashboard': typeof appDashboardRoute
  '/integrations': typeof appIntegrationsRoute
  '/inventory': typeof appInventoryRoute
  '/live-orders': typeof appLiveOrdersRoute
  '/menu': typeof appMenuRoute
  '/menu-mapping': typeof appMenuMappingRoute
  '/reports': typeof appReportsRouteWithChildren
  '/settings': typeof appSettingsRoute
  '/sync-logs': typeof appSyncLogsRoute
  '/test': typeof appTestRoute
  '/users': typeof appUsersRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/reports/monthly-revenue': typeof appReportsMonthlyRevenueRoute
  '/reports/sales-summary': typeof appReportsSalesSummaryRoute
  '/reports/stock-levels': typeof appReportsStockLevelsRoute
  '/reports/': typeof appReportsIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/about': typeof appAboutRoute
  '/analytics': typeof appAnalyticsRoute
  '/dashboard': typeof appDashboardRoute
  '/integrations': typeof appIntegrationsRoute
  '/inventory': typeof appInventoryRoute
  '/live-orders': typeof appLiveOrdersRoute
  '/menu': typeof appMenuRoute
  '/menu-mapping': typeof appMenuMappingRoute
  '/settings': typeof appSettingsRoute
  '/sync-logs': typeof appSyncLogsRoute
  '/test': typeof appTestRoute
  '/users': typeof appUsersRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/reports/monthly-revenue': typeof appReportsMonthlyRevenueRoute
  '/reports/sales-summary': typeof appReportsSalesSummaryRoute
  '/reports/stock-levels': typeof appReportsStockLevelsRoute
  '/reports': typeof appReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/(app)/about': typeof appAboutRoute
  '/(app)/analytics': typeof appAnalyticsRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/integrations': typeof appIntegrationsRoute
  '/(app)/inventory': typeof appInventoryRoute
  '/(app)/live-orders': typeof appLiveOrdersRoute
  '/(app)/menu': typeof appMenuRoute
  '/(app)/menu-mapping': typeof appMenuMappingRoute
  '/(app)/reports': typeof appReportsRouteWithChildren
  '/(app)/settings': typeof appSettingsRoute
  '/(app)/sync-logs': typeof appSyncLogsRoute
  '/(app)/test': typeof appTestRoute
  '/(app)/users': typeof appUsersRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/reports/monthly-revenue': typeof appReportsMonthlyRevenueRoute
  '/(app)/reports/sales-summary': typeof appReportsSalesSummaryRoute
  '/(app)/reports/stock-levels': typeof appReportsStockLevelsRoute
  '/(app)/reports/': typeof appReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/accept-invite'
    | '/admin'
    | '/about'
    | '/analytics'
    | '/dashboard'
    | '/integrations'
    | '/inventory'
    | '/live-orders'
    | '/menu'
    | '/menu-mapping'
    | '/reports'
    | '/settings'
    | '/sync-logs'
    | '/test'
    | '/users'
    | '/login'
    | '/signup'
    | '/'
    | '/reports/monthly-revenue'
    | '/reports/sales-summary'
    | '/reports/stock-levels'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/admin'
    | '/about'
    | '/analytics'
    | '/dashboard'
    | '/integrations'
    | '/inventory'
    | '/live-orders'
    | '/menu'
    | '/menu-mapping'
    | '/settings'
    | '/sync-logs'
    | '/test'
    | '/users'
    | '/login'
    | '/signup'
    | '/'
    | '/reports/monthly-revenue'
    | '/reports/sales-summary'
    | '/reports/stock-levels'
    | '/reports'
  id:
    | '__root__'
    | '/(app)'
    | '/accept-invite'
    | '/admin'
    | '/(app)/about'
    | '/(app)/analytics'
    | '/(app)/dashboard'
    | '/(app)/integrations'
    | '/(app)/inventory'
    | '/(app)/live-orders'
    | '/(app)/menu'
    | '/(app)/menu-mapping'
    | '/(app)/reports'
    | '/(app)/settings'
    | '/(app)/sync-logs'
    | '/(app)/test'
    | '/(app)/users'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(app)/'
    | '/(app)/reports/monthly-revenue'
    | '/(app)/reports/sales-summary'
    | '/(app)/reports/stock-levels'
    | '/(app)/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AdminRoute: typeof AdminRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/users': {
      id: '/(app)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof appUsersRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/test': {
      id: '/(app)/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof appTestRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/sync-logs': {
      id: '/(app)/sync-logs'
      path: '/sync-logs'
      fullPath: '/sync-logs'
      preLoaderRoute: typeof appSyncLogsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/reports': {
      id: '/(app)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof appReportsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/menu-mapping': {
      id: '/(app)/menu-mapping'
      path: '/menu-mapping'
      fullPath: '/menu-mapping'
      preLoaderRoute: typeof appMenuMappingRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/menu': {
      id: '/(app)/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof appMenuRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/live-orders': {
      id: '/(app)/live-orders'
      path: '/live-orders'
      fullPath: '/live-orders'
      preLoaderRoute: typeof appLiveOrdersRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/inventory': {
      id: '/(app)/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof appInventoryRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/integrations': {
      id: '/(app)/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof appIntegrationsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/analytics': {
      id: '/(app)/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof appAnalyticsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/about': {
      id: '/(app)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appAboutRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/reports/': {
      id: '/(app)/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof appReportsIndexRouteImport
      parentRoute: typeof appReportsRoute
    }
    '/(app)/reports/stock-levels': {
      id: '/(app)/reports/stock-levels'
      path: '/stock-levels'
      fullPath: '/reports/stock-levels'
      preLoaderRoute: typeof appReportsStockLevelsRouteImport
      parentRoute: typeof appReportsRoute
    }
    '/(app)/reports/sales-summary': {
      id: '/(app)/reports/sales-summary'
      path: '/sales-summary'
      fullPath: '/reports/sales-summary'
      preLoaderRoute: typeof appReportsSalesSummaryRouteImport
      parentRoute: typeof appReportsRoute
    }
    '/(app)/reports/monthly-revenue': {
      id: '/(app)/reports/monthly-revenue'
      path: '/monthly-revenue'
      fullPath: '/reports/monthly-revenue'
      preLoaderRoute: typeof appReportsMonthlyRevenueRouteImport
      parentRoute: typeof appReportsRoute
    }
  }
}

interface appReportsRouteChildren {
  appReportsMonthlyRevenueRoute: typeof appReportsMonthlyRevenueRoute
  appReportsSalesSummaryRoute: typeof appReportsSalesSummaryRoute
  appReportsStockLevelsRoute: typeof appReportsStockLevelsRoute
  appReportsIndexRoute: typeof appReportsIndexRoute
}

const appReportsRouteChildren: appReportsRouteChildren = {
  appReportsMonthlyRevenueRoute: appReportsMonthlyRevenueRoute,
  appReportsSalesSummaryRoute: appReportsSalesSummaryRoute,
  appReportsStockLevelsRoute: appReportsStockLevelsRoute,
  appReportsIndexRoute: appReportsIndexRoute,
}

const appReportsRouteWithChildren = appReportsRoute._addFileChildren(
  appReportsRouteChildren,
)

interface appRouteRouteChildren {
  appAboutRoute: typeof appAboutRoute
  appAnalyticsRoute: typeof appAnalyticsRoute
  appDashboardRoute: typeof appDashboardRoute
  appIntegrationsRoute: typeof appIntegrationsRoute
  appInventoryRoute: typeof appInventoryRoute
  appLiveOrdersRoute: typeof appLiveOrdersRoute
  appMenuRoute: typeof appMenuRoute
  appMenuMappingRoute: typeof appMenuMappingRoute
  appReportsRoute: typeof appReportsRouteWithChildren
  appSettingsRoute: typeof appSettingsRoute
  appSyncLogsRoute: typeof appSyncLogsRoute
  appTestRoute: typeof appTestRoute
  appUsersRoute: typeof appUsersRoute
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAboutRoute: appAboutRoute,
  appAnalyticsRoute: appAnalyticsRoute,
  appDashboardRoute: appDashboardRoute,
  appIntegrationsRoute: appIntegrationsRoute,
  appInventoryRoute: appInventoryRoute,
  appLiveOrdersRoute: appLiveOrdersRoute,
  appMenuRoute: appMenuRoute,
  appMenuMappingRoute: appMenuMappingRoute,
  appReportsRoute: appReportsRouteWithChildren,
  appSettingsRoute: appSettingsRoute,
  appSyncLogsRoute: appSyncLogsRoute,
  appTestRoute: appTestRoute,
  appUsersRoute: appUsersRoute,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
